# Generated by Django 5.1.4 on 2026-01-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=10)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('allotted', 'Allotted'), ('cleaned', 'Cleaned'), ('dirty', 'Dirty')], default='available', max_length=10)),
            ],
        ),
    ]
